import { splitProps, type ComponentProps } from "solid-js"
import { Dynamic } from "solid-js/web"
import {
  IconFile,
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconArchive,
  IconArrowBackUp,
  IconArrowBarToRight,
  IconArrowFork,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowsSort,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconBan,
  IconBox,
  IconBrain,
  IconBrandDiscord,
  IconBrandGithub,
  IconBrowser,
  IconCheck,
  IconChevronUp,
  IconInfoSquare,
  IconArrowDown,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsRight,
  IconCircleCheck,
  IconCircleX,
  IconClipboardCheck,
  IconCloudUpload,
  IconCode,
  IconCodeDots,
  IconCopy,
  IconCornerDownLeft,
  IconDeviceDesktop,
  IconDots,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeglass,
  IconFileDiff,
  IconFileExport,
  IconFolder,
  IconFolderDown,
  IconFolders,
  IconFolderOpen,
  IconFolderCode,
  IconFolderPlus,
  IconGitBranch,
  IconGripVertical,
  IconHelpCircle,
  IconHierarchy,
  IconKeyboard,
  IconLayoutBottombar,
  IconLayoutBottombarFilled,
  IconLayoutColumns,
  IconLayoutGridAdd,
  IconLayoutList,
  IconLayoutSidebar,
  IconLayoutSidebarFilled,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLayoutSidebarRight,
  IconLayoutSidebarRightCollapse,
  IconLayoutSidebarRightExpand,
  IconLayoutSidebarRightFilled,
  IconLink,
  IconUnlink,
  IconList,
  IconListCheck,
  IconListSearch,
  IconLoader2,
  IconMenu2,
  IconMessage,
  IconMessages,
  IconMicrophone,
  IconMinus,
  IconPencil,
  IconPhoto,
  IconPlayerPauseFilled,
  IconPlayerPlayFilled,
  IconPlayerStopFilled,
  IconPlug,
  IconPlugConnected,
  IconPlus,
  IconRestore,
  IconRobot,
  IconSearch,
  IconSelector,
  IconServer,
  IconSettings,
  IconShare,
  IconShield,
  IconSparkles,
  IconTerminal2,
  IconTrash,
  IconX,
} from "@tabler/icons-solidjs"

// App roles and existing names share one map so callers do not depend on Tabler names.
export const icons = {
  chevronUp: IconChevronUp,
  infoSquare: IconInfoSquare,
  arrowDown: IconArrowDown,
  "align-right": IconArrowBarToRight,
  "arrow-up": IconArrowUp,
  "arrows-sort": IconArrowsSort,
  "arrow-left": IconArrowLeft,
  "arrow-right": IconArrowRight,
  archive: IconArchive,
  "bubble-5": IconMessage,
  prompt: IconMessages,
  brain: IconBrain,
  fork: IconArrowFork,
  "bullet-list": IconList,
  "check-small": IconCheck,
  "chevron-down": IconChevronDown,
  "chevron-left": IconChevronLeft,
  "chevron-right": IconChevronRight,
  "chevron-grabber-vertical": IconSelector,
  "chevron-double-right": IconChevronsRight,
  "circle-x": IconCircleX,
  close: IconX,
  "close-small": IconX,
  checklist: IconListCheck,
  console: IconTerminal2,
  terminal: IconTerminal2,
  "terminal-active": IconTerminal2,
  review: IconFileDiff,
  "review-active": IconFileDiff,
  expand: IconArrowsMaximize,
  collapse: IconArrowsMinimize,
  code: IconCode,
  "code-lines": IconCodeDots,
  "circle-ban-sign": IconBan,
  "edit-small-2": IconPencil,
  eye: IconEye,
  enter: IconCornerDownLeft,
  file: IconFile,
  folder: IconFolder,
  "folder-down": IconFolderDown,
  folders: IconFolders,
  folderOpen: IconFolderOpen,
  "file-tree": IconHierarchy,
  "file-tree-active": IconHierarchy,
  "magnifying-glass": IconSearch,
  "plus-small": IconPlus,
  plus: IconPlus,
  "new-session": IconEdit,
  "new-session-active": IconEdit,
  "pencil-line": IconPencil,
  mcp: IconPlugConnected,
  glasses: IconEyeglass,
  "magnifying-glass-menu": IconListSearch,
  "window-cursor": IconBrowser,
  task: IconClipboardCheck,
  subagent: IconRobot,
  stop: IconPlayerStopFilled,
  status: IconActivity,
  "status-active": IconActivity,
  sidebar: IconLayoutSidebarLeftExpand,
  "sidebar-active": IconLayoutSidebarLeftCollapse,
  "layout-left": IconLayoutSidebar,
  "layout-left-partial": IconLayoutSidebar,
  "layout-left-full": IconLayoutSidebarFilled,
  "layout-right": IconLayoutSidebarRight,
  "layout-right-partial": IconLayoutSidebarRight,
  "layout-right-full": IconLayoutSidebarRightFilled,
  "square-arrow-top-right": IconExternalLink,
  "open-file": IconFileExport,
  "speech-bubble": IconMessage,
  comment: IconMessage,
  "folder-add-left": IconFolderPlus,
  github: IconBrandGithub,
  discord: IconBrandDiscord,
  "layout-bottom": IconLayoutBottombar,
  "layout-bottom-partial": IconLayoutBottombar,
  "layout-bottom-full": IconLayoutBottombarFilled,
  "dot-grid": IconGripVertical,
  "circle-check": IconCircleCheck,
  copy: IconCopy,
  check: IconCheck,
  photo: IconPhoto,
  share: IconShare,
  shield: IconShield,
  download: IconDownload,
  menu: IconMenu2,
  server: IconServer,
  branch: IconGitBranch,
  edit: IconEdit,
  help: IconHelpCircle,
  "settings-gear": IconSettings,
  dash: IconMinus,
  "cloud-upload": IconCloudUpload,
  trash: IconTrash,
  sliders: IconAdjustmentsHorizontal,
  keyboard: IconKeyboard,
  selector: IconSelector,
  "arrow-down-to-line": IconDownload,
  warning: IconAlertTriangle,
  reset: IconRestore,
  link: IconLink,
  unlink: IconUnlink,
  providers: IconPlug,
  provider: IconSparkles,
  models: IconBrain,
  "arrow-undo-down": IconArrowBackUp,
  "grid-plus": IconLayoutGridAdd,
  "sidebar-right": IconLayoutSidebarRight,
  monitor: IconDeviceDesktop,
  "workspace-new": IconFolderPlus,
  "workspace-isolated": IconBox,
  workspace: IconFolderCode,
  "xmark-small": IconX,
  "outline-xmark": IconX,
  "outline-chevron-down": IconChevronDown,
  "outline-dots": IconDots,
  filetree: IconHierarchy,
  split: IconLayoutColumns,
  unified: IconLayoutList,
  "outline-sliders": IconAdjustmentsHorizontal,
  "outline-copy": IconCopy,
  "outline-square-arrow": IconExternalLink,
  "outline-share": IconShare,
  "outline-reset": IconRestore,
  sidebarOpen: IconLayoutSidebarLeftExpand,
  sidebarClose: IconLayoutSidebarLeftCollapse,
  rightPanelOpen: IconLayoutSidebarRightExpand,
  rightPanelClose: IconLayoutSidebarRightCollapse,
  sessionLoading: IconLoader2,
  voiceInput: IconMicrophone,
  voiceStop: IconPlayerStopFilled,
  voicePlay: IconPlayerPlayFilled,
  voicePause: IconPlayerPauseFilled,
  voiceCancel: IconX,
} as const

export interface TablerIconProps extends ComponentProps<"svg"> {
  name: keyof typeof icons
  size?: number | string
}

export function TablerIcon(props: TablerIconProps) {
  const [local, rest] = splitProps(props, ["name", "size", "width", "height"])
  return (
    <Dynamic
      component={icons[local.name]}
      size={local.size ?? local.width ?? local.height ?? 20}
      stroke="1.75"
      aria-hidden="true"
      {...rest}
      data-icon-source="tabler"
      data-icon-role={local.name}
    />
  )
}
